//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2025-10-24 10:08:03
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SDRAM_CSR_H
#define __GENERATED_SDRAM_CSR_H

/* sdram */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_SDRAM_BASE
#define CSR_SDRAM_BASE (CSR_BASE + 0x800L)
#define CSR_SDRAM_DFII_CONTROL_ADDR (CSR_SDRAM_BASE + 0x0L)
#define CSR_SDRAM_DFII_CONTROL_SIZE 1
static inline uint32_t sdram_dfii_control_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_CONTROL_ADDR)));
}
static inline void sdram_dfii_control_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_CONTROL_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_CONTROL_SEL_OFFSET 0
#define CSR_SDRAM_DFII_CONTROL_SEL_SIZE 1
static inline uint32_t sdram_dfii_control_sel_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t sdram_dfii_control_sel_read(uint32_t a32) {
	uint32_t word = sdram_dfii_control_read(a32);
	return sdram_dfii_control_sel_extract(a32, word);
}
static inline uint32_t sdram_dfii_control_sel_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void sdram_dfii_control_sel_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_control_read(a32);
	uint32_t newword = sdram_dfii_control_sel_replace(a32, oldword, plain_value);
	sdram_dfii_control_write(a32, newword);
}
#define CSR_SDRAM_DFII_CONTROL_CKE_OFFSET 1
#define CSR_SDRAM_DFII_CONTROL_CKE_SIZE 1
static inline uint32_t sdram_dfii_control_cke_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t sdram_dfii_control_cke_read(uint32_t a32) {
	uint32_t word = sdram_dfii_control_read(a32);
	return sdram_dfii_control_cke_extract(a32, word);
}
static inline uint32_t sdram_dfii_control_cke_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void sdram_dfii_control_cke_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_control_read(a32);
	uint32_t newword = sdram_dfii_control_cke_replace(a32, oldword, plain_value);
	sdram_dfii_control_write(a32, newword);
}
#define CSR_SDRAM_DFII_CONTROL_ODT_OFFSET 2
#define CSR_SDRAM_DFII_CONTROL_ODT_SIZE 1
static inline uint32_t sdram_dfii_control_odt_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t sdram_dfii_control_odt_read(uint32_t a32) {
	uint32_t word = sdram_dfii_control_read(a32);
	return sdram_dfii_control_odt_extract(a32, word);
}
static inline uint32_t sdram_dfii_control_odt_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void sdram_dfii_control_odt_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_control_read(a32);
	uint32_t newword = sdram_dfii_control_odt_replace(a32, oldword, plain_value);
	sdram_dfii_control_write(a32, newword);
}
#define CSR_SDRAM_DFII_CONTROL_RESET_N_OFFSET 3
#define CSR_SDRAM_DFII_CONTROL_RESET_N_SIZE 1
static inline uint32_t sdram_dfii_control_reset_n_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 3) & mask );
}
static inline uint32_t sdram_dfii_control_reset_n_read(uint32_t a32) {
	uint32_t word = sdram_dfii_control_read(a32);
	return sdram_dfii_control_reset_n_extract(a32, word);
}
static inline uint32_t sdram_dfii_control_reset_n_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 3))) | (mask & plain_value)<< 3 ;
}
static inline void sdram_dfii_control_reset_n_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_control_read(a32);
	uint32_t newword = sdram_dfii_control_reset_n_replace(a32, oldword, plain_value);
	sdram_dfii_control_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_ADDR (CSR_SDRAM_BASE + 0x4L)
#define CSR_SDRAM_DFII_PI0_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_COMMAND_ADDR)));
}
static inline void sdram_dfii_pi0_command_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_COMMAND_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_CS_OFFSET 0
#define CSR_SDRAM_DFII_PI0_COMMAND_CS_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_cs_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_cs_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_cs_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_cs_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void sdram_dfii_pi0_command_cs_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_cs_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_WE_OFFSET 1
#define CSR_SDRAM_DFII_PI0_COMMAND_WE_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_we_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_we_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_we_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_we_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void sdram_dfii_pi0_command_we_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_we_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_CAS_OFFSET 2
#define CSR_SDRAM_DFII_PI0_COMMAND_CAS_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_cas_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_cas_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_cas_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_cas_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void sdram_dfii_pi0_command_cas_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_cas_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_RAS_OFFSET 3
#define CSR_SDRAM_DFII_PI0_COMMAND_RAS_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_ras_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 3) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_ras_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_ras_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_ras_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 3))) | (mask & plain_value)<< 3 ;
}
static inline void sdram_dfii_pi0_command_ras_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_ras_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_WREN_OFFSET 4
#define CSR_SDRAM_DFII_PI0_COMMAND_WREN_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_wren_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 4) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_wren_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_wren_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_wren_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 4))) | (mask & plain_value)<< 4 ;
}
static inline void sdram_dfii_pi0_command_wren_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_wren_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_RDEN_OFFSET 5
#define CSR_SDRAM_DFII_PI0_COMMAND_RDEN_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_rden_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t sdram_dfii_pi0_command_rden_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi0_command_read(a32);
	return sdram_dfii_pi0_command_rden_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi0_command_rden_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void sdram_dfii_pi0_command_rden_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi0_command_read(a32);
	uint32_t newword = sdram_dfii_pi0_command_rden_replace(a32, oldword, plain_value);
	sdram_dfii_pi0_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_ADDR (CSR_SDRAM_BASE + 0x8L)
#define CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_issue_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_ADDR)));
}
static inline void sdram_dfii_pi0_command_issue_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI0_ADDRESS_ADDR (CSR_SDRAM_BASE + 0xcL)
#define CSR_SDRAM_DFII_PI0_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi0_address_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_ADDRESS_ADDR)));
}
static inline void sdram_dfii_pi0_address_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_ADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI0_BADDRESS_ADDR (CSR_SDRAM_BASE + 0x10L)
#define CSR_SDRAM_DFII_PI0_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi0_baddress_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_BADDRESS_ADDR)));
}
static inline void sdram_dfii_pi0_baddress_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_BADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI0_WRDATA_ADDR (CSR_SDRAM_BASE + 0x14L)
#define CSR_SDRAM_DFII_PI0_WRDATA_SIZE 1
static inline uint32_t sdram_dfii_pi0_wrdata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_WRDATA_ADDR)));
}
static inline void sdram_dfii_pi0_wrdata_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_WRDATA_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI0_RDDATA_ADDR (CSR_SDRAM_BASE + 0x18L)
#define CSR_SDRAM_DFII_PI0_RDDATA_SIZE 1
static inline uint32_t sdram_dfii_pi0_rddata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI0_RDDATA_ADDR)));
}
#define CSR_SDRAM_DFII_PI1_COMMAND_ADDR (CSR_SDRAM_BASE + 0x1cL)
#define CSR_SDRAM_DFII_PI1_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_COMMAND_ADDR)));
}
static inline void sdram_dfii_pi1_command_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_COMMAND_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_CS_OFFSET 0
#define CSR_SDRAM_DFII_PI1_COMMAND_CS_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_cs_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_cs_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_cs_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_cs_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void sdram_dfii_pi1_command_cs_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_cs_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_WE_OFFSET 1
#define CSR_SDRAM_DFII_PI1_COMMAND_WE_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_we_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_we_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_we_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_we_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void sdram_dfii_pi1_command_we_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_we_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_CAS_OFFSET 2
#define CSR_SDRAM_DFII_PI1_COMMAND_CAS_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_cas_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_cas_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_cas_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_cas_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void sdram_dfii_pi1_command_cas_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_cas_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_RAS_OFFSET 3
#define CSR_SDRAM_DFII_PI1_COMMAND_RAS_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_ras_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 3) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_ras_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_ras_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_ras_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 3))) | (mask & plain_value)<< 3 ;
}
static inline void sdram_dfii_pi1_command_ras_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_ras_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_WREN_OFFSET 4
#define CSR_SDRAM_DFII_PI1_COMMAND_WREN_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_wren_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 4) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_wren_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_wren_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_wren_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 4))) | (mask & plain_value)<< 4 ;
}
static inline void sdram_dfii_pi1_command_wren_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_wren_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_RDEN_OFFSET 5
#define CSR_SDRAM_DFII_PI1_COMMAND_RDEN_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_rden_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t sdram_dfii_pi1_command_rden_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi1_command_read(a32);
	return sdram_dfii_pi1_command_rden_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi1_command_rden_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void sdram_dfii_pi1_command_rden_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi1_command_read(a32);
	uint32_t newword = sdram_dfii_pi1_command_rden_replace(a32, oldword, plain_value);
	sdram_dfii_pi1_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_ADDR (CSR_SDRAM_BASE + 0x20L)
#define CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_issue_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_ADDR)));
}
static inline void sdram_dfii_pi1_command_issue_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI1_ADDRESS_ADDR (CSR_SDRAM_BASE + 0x24L)
#define CSR_SDRAM_DFII_PI1_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi1_address_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_ADDRESS_ADDR)));
}
static inline void sdram_dfii_pi1_address_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_ADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI1_BADDRESS_ADDR (CSR_SDRAM_BASE + 0x28L)
#define CSR_SDRAM_DFII_PI1_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi1_baddress_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_BADDRESS_ADDR)));
}
static inline void sdram_dfii_pi1_baddress_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_BADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI1_WRDATA_ADDR (CSR_SDRAM_BASE + 0x2cL)
#define CSR_SDRAM_DFII_PI1_WRDATA_SIZE 1
static inline uint32_t sdram_dfii_pi1_wrdata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_WRDATA_ADDR)));
}
static inline void sdram_dfii_pi1_wrdata_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_WRDATA_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI1_RDDATA_ADDR (CSR_SDRAM_BASE + 0x30L)
#define CSR_SDRAM_DFII_PI1_RDDATA_SIZE 1
static inline uint32_t sdram_dfii_pi1_rddata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI1_RDDATA_ADDR)));
}
#define CSR_SDRAM_DFII_PI2_COMMAND_ADDR (CSR_SDRAM_BASE + 0x34L)
#define CSR_SDRAM_DFII_PI2_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_COMMAND_ADDR)));
}
static inline void sdram_dfii_pi2_command_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_COMMAND_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_CS_OFFSET 0
#define CSR_SDRAM_DFII_PI2_COMMAND_CS_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_cs_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_cs_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_cs_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_cs_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void sdram_dfii_pi2_command_cs_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_cs_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_WE_OFFSET 1
#define CSR_SDRAM_DFII_PI2_COMMAND_WE_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_we_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_we_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_we_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_we_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void sdram_dfii_pi2_command_we_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_we_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_CAS_OFFSET 2
#define CSR_SDRAM_DFII_PI2_COMMAND_CAS_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_cas_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_cas_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_cas_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_cas_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void sdram_dfii_pi2_command_cas_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_cas_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_RAS_OFFSET 3
#define CSR_SDRAM_DFII_PI2_COMMAND_RAS_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_ras_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 3) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_ras_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_ras_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_ras_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 3))) | (mask & plain_value)<< 3 ;
}
static inline void sdram_dfii_pi2_command_ras_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_ras_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_WREN_OFFSET 4
#define CSR_SDRAM_DFII_PI2_COMMAND_WREN_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_wren_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 4) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_wren_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_wren_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_wren_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 4))) | (mask & plain_value)<< 4 ;
}
static inline void sdram_dfii_pi2_command_wren_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_wren_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_RDEN_OFFSET 5
#define CSR_SDRAM_DFII_PI2_COMMAND_RDEN_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_rden_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t sdram_dfii_pi2_command_rden_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi2_command_read(a32);
	return sdram_dfii_pi2_command_rden_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi2_command_rden_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void sdram_dfii_pi2_command_rden_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi2_command_read(a32);
	uint32_t newword = sdram_dfii_pi2_command_rden_replace(a32, oldword, plain_value);
	sdram_dfii_pi2_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI2_COMMAND_ISSUE_ADDR (CSR_SDRAM_BASE + 0x38L)
#define CSR_SDRAM_DFII_PI2_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi2_command_issue_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_COMMAND_ISSUE_ADDR)));
}
static inline void sdram_dfii_pi2_command_issue_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_COMMAND_ISSUE_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI2_ADDRESS_ADDR (CSR_SDRAM_BASE + 0x3cL)
#define CSR_SDRAM_DFII_PI2_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi2_address_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_ADDRESS_ADDR)));
}
static inline void sdram_dfii_pi2_address_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_ADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI2_BADDRESS_ADDR (CSR_SDRAM_BASE + 0x40L)
#define CSR_SDRAM_DFII_PI2_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi2_baddress_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_BADDRESS_ADDR)));
}
static inline void sdram_dfii_pi2_baddress_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_BADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI2_WRDATA_ADDR (CSR_SDRAM_BASE + 0x44L)
#define CSR_SDRAM_DFII_PI2_WRDATA_SIZE 1
static inline uint32_t sdram_dfii_pi2_wrdata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_WRDATA_ADDR)));
}
static inline void sdram_dfii_pi2_wrdata_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_WRDATA_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI2_RDDATA_ADDR (CSR_SDRAM_BASE + 0x48L)
#define CSR_SDRAM_DFII_PI2_RDDATA_SIZE 1
static inline uint32_t sdram_dfii_pi2_rddata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI2_RDDATA_ADDR)));
}
#define CSR_SDRAM_DFII_PI3_COMMAND_ADDR (CSR_SDRAM_BASE + 0x4cL)
#define CSR_SDRAM_DFII_PI3_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_COMMAND_ADDR)));
}
static inline void sdram_dfii_pi3_command_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_COMMAND_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_CS_OFFSET 0
#define CSR_SDRAM_DFII_PI3_COMMAND_CS_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_cs_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_cs_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_cs_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_cs_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void sdram_dfii_pi3_command_cs_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_cs_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_WE_OFFSET 1
#define CSR_SDRAM_DFII_PI3_COMMAND_WE_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_we_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_we_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_we_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_we_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void sdram_dfii_pi3_command_we_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_we_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_CAS_OFFSET 2
#define CSR_SDRAM_DFII_PI3_COMMAND_CAS_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_cas_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_cas_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_cas_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_cas_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void sdram_dfii_pi3_command_cas_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_cas_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_RAS_OFFSET 3
#define CSR_SDRAM_DFII_PI3_COMMAND_RAS_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_ras_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 3) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_ras_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_ras_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_ras_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 3))) | (mask & plain_value)<< 3 ;
}
static inline void sdram_dfii_pi3_command_ras_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_ras_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_WREN_OFFSET 4
#define CSR_SDRAM_DFII_PI3_COMMAND_WREN_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_wren_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 4) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_wren_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_wren_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_wren_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 4))) | (mask & plain_value)<< 4 ;
}
static inline void sdram_dfii_pi3_command_wren_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_wren_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_RDEN_OFFSET 5
#define CSR_SDRAM_DFII_PI3_COMMAND_RDEN_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_rden_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t sdram_dfii_pi3_command_rden_read(uint32_t a32) {
	uint32_t word = sdram_dfii_pi3_command_read(a32);
	return sdram_dfii_pi3_command_rden_extract(a32, word);
}
static inline uint32_t sdram_dfii_pi3_command_rden_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void sdram_dfii_pi3_command_rden_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = sdram_dfii_pi3_command_read(a32);
	uint32_t newword = sdram_dfii_pi3_command_rden_replace(a32, oldword, plain_value);
	sdram_dfii_pi3_command_write(a32, newword);
}
#define CSR_SDRAM_DFII_PI3_COMMAND_ISSUE_ADDR (CSR_SDRAM_BASE + 0x50L)
#define CSR_SDRAM_DFII_PI3_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi3_command_issue_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_COMMAND_ISSUE_ADDR)));
}
static inline void sdram_dfii_pi3_command_issue_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_COMMAND_ISSUE_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI3_ADDRESS_ADDR (CSR_SDRAM_BASE + 0x54L)
#define CSR_SDRAM_DFII_PI3_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi3_address_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_ADDRESS_ADDR)));
}
static inline void sdram_dfii_pi3_address_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_ADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI3_BADDRESS_ADDR (CSR_SDRAM_BASE + 0x58L)
#define CSR_SDRAM_DFII_PI3_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi3_baddress_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_BADDRESS_ADDR)));
}
static inline void sdram_dfii_pi3_baddress_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_BADDRESS_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI3_WRDATA_ADDR (CSR_SDRAM_BASE + 0x5cL)
#define CSR_SDRAM_DFII_PI3_WRDATA_SIZE 1
static inline uint32_t sdram_dfii_pi3_wrdata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_WRDATA_ADDR)));
}
static inline void sdram_dfii_pi3_wrdata_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_WRDATA_ADDR + 0)) = __builtin_bswap32(v);
}
#define CSR_SDRAM_DFII_PI3_RDDATA_ADDR (CSR_SDRAM_BASE + 0x60L)
#define CSR_SDRAM_DFII_PI3_RDDATA_SIZE 1
static inline uint32_t sdram_dfii_pi3_rddata_read(uint32_t a32) {
	return __builtin_bswap32(*((volatile uint32_t*)(a32 + CSR_SDRAM_DFII_PI3_RDDATA_ADDR)));
}
#endif // CSR_SDRAM_BASE

#endif
