//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2026-02-13 15:07:54
//--------------------------------------------------------------------------------
#ifndef __GENERATED_ZZ02_MDIO_CSR_H
#define __GENERATED_ZZ02_MDIO_CSR_H

/* zz02_mdio */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_ZZ02_MDIO_BASE
#define CSR_ZZ02_MDIO_BASE (CSR_BASE + 0x1800L)
#define CSR_ZZ02_MDIO_REG_ADDR_ADDR (CSR_ZZ02_MDIO_BASE + 0x0L)
#define CSR_ZZ02_MDIO_REG_ADDR_SIZE 1
static inline uint32_t zz02_mdio_reg_addr_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_REG_ADDR_ADDR)));
}
static inline void zz02_mdio_reg_addr_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_REG_ADDR_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ02_MDIO_REG_ADDR_REG_ADDR_OFFSET 0
#define CSR_ZZ02_MDIO_REG_ADDR_REG_ADDR_SIZE 5
static inline uint32_t zz02_mdio_reg_addr_reg_addr_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 5)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_reg_addr_reg_addr_read(uint32_t a32) {
	uint32_t word = zz02_mdio_reg_addr_read(a32);
	return zz02_mdio_reg_addr_reg_addr_extract(a32, word);
}
static inline uint32_t zz02_mdio_reg_addr_reg_addr_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 5)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz02_mdio_reg_addr_reg_addr_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_reg_addr_read(a32);
	uint32_t newword = zz02_mdio_reg_addr_reg_addr_replace(a32, oldword, plain_value);
	zz02_mdio_reg_addr_write(a32, newword);
}
#define CSR_ZZ02_MDIO_REG_ADDR_RESERVED_OFFSET 5
#define CSR_ZZ02_MDIO_REG_ADDR_RESERVED_SIZE 27
static inline uint32_t zz02_mdio_reg_addr_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 27)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t zz02_mdio_reg_addr_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_reg_addr_read(a32);
	return zz02_mdio_reg_addr_reserved_extract(a32, word);
}
static inline uint32_t zz02_mdio_reg_addr_reserved_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 27)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void zz02_mdio_reg_addr_reserved_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_reg_addr_read(a32);
	uint32_t newword = zz02_mdio_reg_addr_reserved_replace(a32, oldword, plain_value);
	zz02_mdio_reg_addr_write(a32, newword);
}
#define CSR_ZZ02_MDIO_PHY_ADDR_ADDR (CSR_ZZ02_MDIO_BASE + 0x4L)
#define CSR_ZZ02_MDIO_PHY_ADDR_SIZE 1
static inline uint32_t zz02_mdio_phy_addr_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_PHY_ADDR_ADDR)));
}
static inline void zz02_mdio_phy_addr_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_PHY_ADDR_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ02_MDIO_PHY_ADDR_PHY_ADDR_OFFSET 0
#define CSR_ZZ02_MDIO_PHY_ADDR_PHY_ADDR_SIZE 5
static inline uint32_t zz02_mdio_phy_addr_phy_addr_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 5)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_phy_addr_phy_addr_read(uint32_t a32) {
	uint32_t word = zz02_mdio_phy_addr_read(a32);
	return zz02_mdio_phy_addr_phy_addr_extract(a32, word);
}
static inline uint32_t zz02_mdio_phy_addr_phy_addr_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 5)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz02_mdio_phy_addr_phy_addr_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_phy_addr_read(a32);
	uint32_t newword = zz02_mdio_phy_addr_phy_addr_replace(a32, oldword, plain_value);
	zz02_mdio_phy_addr_write(a32, newword);
}
#define CSR_ZZ02_MDIO_PHY_ADDR_RESERVED_OFFSET 5
#define CSR_ZZ02_MDIO_PHY_ADDR_RESERVED_SIZE 27
static inline uint32_t zz02_mdio_phy_addr_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 27)-1);
	return ( (oldword >> 5) & mask );
}
static inline uint32_t zz02_mdio_phy_addr_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_phy_addr_read(a32);
	return zz02_mdio_phy_addr_reserved_extract(a32, word);
}
static inline uint32_t zz02_mdio_phy_addr_reserved_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 27)-1);
	return (oldword & (~(mask << 5))) | (mask & plain_value)<< 5 ;
}
static inline void zz02_mdio_phy_addr_reserved_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_phy_addr_read(a32);
	uint32_t newword = zz02_mdio_phy_addr_reserved_replace(a32, oldword, plain_value);
	zz02_mdio_phy_addr_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_COMMAND_ADDR (CSR_ZZ02_MDIO_BASE + 0x8L)
#define CSR_ZZ02_MDIO_MDIO_COMMAND_SIZE 1
static inline uint32_t zz02_mdio_mdio_command_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_COMMAND_ADDR)));
}
static inline void zz02_mdio_mdio_command_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_COMMAND_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ02_MDIO_MDIO_COMMAND_READ_OFFSET 0
#define CSR_ZZ02_MDIO_MDIO_COMMAND_READ_SIZE 1
static inline uint32_t zz02_mdio_mdio_command_read_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_mdio_command_read_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_command_read(a32);
	return zz02_mdio_mdio_command_read_extract(a32, word);
}
static inline uint32_t zz02_mdio_mdio_command_read_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz02_mdio_mdio_command_read_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_mdio_command_read(a32);
	uint32_t newword = zz02_mdio_mdio_command_read_replace(a32, oldword, plain_value);
	zz02_mdio_mdio_command_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_COMMAND_WRITE_OFFSET 1
#define CSR_ZZ02_MDIO_MDIO_COMMAND_WRITE_SIZE 1
static inline uint32_t zz02_mdio_mdio_command_write_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t zz02_mdio_mdio_command_write_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_command_read(a32);
	return zz02_mdio_mdio_command_write_extract(a32, word);
}
static inline uint32_t zz02_mdio_mdio_command_write_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void zz02_mdio_mdio_command_write_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_mdio_command_read(a32);
	uint32_t newword = zz02_mdio_mdio_command_write_replace(a32, oldword, plain_value);
	zz02_mdio_mdio_command_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_COMMAND_RESERVED_OFFSET 2
#define CSR_ZZ02_MDIO_MDIO_COMMAND_RESERVED_SIZE 30
static inline uint32_t zz02_mdio_mdio_command_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 30)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t zz02_mdio_mdio_command_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_command_read(a32);
	return zz02_mdio_mdio_command_reserved_extract(a32, word);
}
static inline uint32_t zz02_mdio_mdio_command_reserved_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 30)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void zz02_mdio_mdio_command_reserved_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_mdio_command_read(a32);
	uint32_t newword = zz02_mdio_mdio_command_reserved_replace(a32, oldword, plain_value);
	zz02_mdio_mdio_command_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_STATUS_ADDR (CSR_ZZ02_MDIO_BASE + 0xcL)
#define CSR_ZZ02_MDIO_MDIO_STATUS_SIZE 1
static inline uint32_t zz02_mdio_mdio_status_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_STATUS_ADDR)));
}
#define CSR_ZZ02_MDIO_MDIO_STATUS_ACCESS_COMPLETE_OFFSET 0
#define CSR_ZZ02_MDIO_MDIO_STATUS_ACCESS_COMPLETE_SIZE 1
static inline uint32_t zz02_mdio_mdio_status_access_complete_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_mdio_status_access_complete_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_status_read(a32);
	return zz02_mdio_mdio_status_access_complete_extract(a32, word);
}
#define CSR_ZZ02_MDIO_MDIO_STATUS_BUSY_OFFSET 1
#define CSR_ZZ02_MDIO_MDIO_STATUS_BUSY_SIZE 1
static inline uint32_t zz02_mdio_mdio_status_busy_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t zz02_mdio_mdio_status_busy_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_status_read(a32);
	return zz02_mdio_mdio_status_busy_extract(a32, word);
}
#define CSR_ZZ02_MDIO_MDIO_STATUS_RESERVED_OFFSET 2
#define CSR_ZZ02_MDIO_MDIO_STATUS_RESERVED_SIZE 30
static inline uint32_t zz02_mdio_mdio_status_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 30)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t zz02_mdio_mdio_status_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_status_read(a32);
	return zz02_mdio_mdio_status_reserved_extract(a32, word);
}
#define CSR_ZZ02_MDIO_MDIO_WRITE_ADDR (CSR_ZZ02_MDIO_BASE + 0x10L)
#define CSR_ZZ02_MDIO_MDIO_WRITE_SIZE 1
static inline uint32_t zz02_mdio_mdio_write_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_WRITE_ADDR)));
}
static inline void zz02_mdio_mdio_write_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_WRITE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ02_MDIO_MDIO_WRITE_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_MDIO_WRITE_VAL_SIZE 16
static inline uint32_t zz02_mdio_mdio_write_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 16)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_mdio_write_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_write_read(a32);
	return zz02_mdio_mdio_write_val_extract(a32, word);
}
static inline uint32_t zz02_mdio_mdio_write_val_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 16)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz02_mdio_mdio_write_val_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_mdio_write_read(a32);
	uint32_t newword = zz02_mdio_mdio_write_val_replace(a32, oldword, plain_value);
	zz02_mdio_mdio_write_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_WRITE_RESERVED_OFFSET 16
#define CSR_ZZ02_MDIO_MDIO_WRITE_RESERVED_SIZE 16
static inline uint32_t zz02_mdio_mdio_write_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 16)-1);
	return ( (oldword >> 16) & mask );
}
static inline uint32_t zz02_mdio_mdio_write_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_write_read(a32);
	return zz02_mdio_mdio_write_reserved_extract(a32, word);
}
static inline uint32_t zz02_mdio_mdio_write_reserved_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 16)-1);
	return (oldword & (~(mask << 16))) | (mask & plain_value)<< 16 ;
}
static inline void zz02_mdio_mdio_write_reserved_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz02_mdio_mdio_write_read(a32);
	uint32_t newword = zz02_mdio_mdio_write_reserved_replace(a32, oldword, plain_value);
	zz02_mdio_mdio_write_write(a32, newword);
}
#define CSR_ZZ02_MDIO_MDIO_READ_ADDR (CSR_ZZ02_MDIO_BASE + 0x14L)
#define CSR_ZZ02_MDIO_MDIO_READ_SIZE 1
static inline uint32_t zz02_mdio_mdio_read_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_MDIO_READ_ADDR)));
}
#define CSR_ZZ02_MDIO_MDIO_READ_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_MDIO_READ_VAL_SIZE 16
static inline uint32_t zz02_mdio_mdio_read_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 16)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_mdio_read_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_read_read(a32);
	return zz02_mdio_mdio_read_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_MDIO_READ_RESERVED_OFFSET 16
#define CSR_ZZ02_MDIO_MDIO_READ_RESERVED_SIZE 16
static inline uint32_t zz02_mdio_mdio_read_reserved_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 16)-1);
	return ( (oldword >> 16) & mask );
}
static inline uint32_t zz02_mdio_mdio_read_reserved_read(uint32_t a32) {
	uint32_t word = zz02_mdio_mdio_read_read(a32);
	return zz02_mdio_mdio_read_reserved_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CST_DEBUG1_ADDR (CSR_ZZ02_MDIO_BASE + 0x18L)
#define CSR_ZZ02_MDIO_CST_DEBUG1_SIZE 1
static inline uint32_t zz02_mdio_cst_debug1_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CST_DEBUG1_ADDR)));
}
#define CSR_ZZ02_MDIO_CST_DEBUG1_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CST_DEBUG1_VAL_SIZE 32
static inline uint32_t zz02_mdio_cst_debug1_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_cst_debug1_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_cst_debug1_read(a32);
	return zz02_mdio_cst_debug1_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CST_DEBUG2_ADDR (CSR_ZZ02_MDIO_BASE + 0x1cL)
#define CSR_ZZ02_MDIO_CST_DEBUG2_SIZE 1
static inline uint32_t zz02_mdio_cst_debug2_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CST_DEBUG2_ADDR)));
}
#define CSR_ZZ02_MDIO_CST_DEBUG2_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CST_DEBUG2_VAL_SIZE 32
static inline uint32_t zz02_mdio_cst_debug2_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_cst_debug2_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_cst_debug2_read(a32);
	return zz02_mdio_cst_debug2_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_0_ADDR (CSR_ZZ02_MDIO_BASE + 0x20L)
#define CSR_ZZ02_MDIO_CSR_IV_0_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_0_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_0_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_0_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_0_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_0_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_0_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_0_read(a32);
	return zz02_mdio_csr_iv_0_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_1_ADDR (CSR_ZZ02_MDIO_BASE + 0x24L)
#define CSR_ZZ02_MDIO_CSR_IV_1_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_1_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_1_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_1_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_1_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_1_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_1_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_1_read(a32);
	return zz02_mdio_csr_iv_1_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_2_ADDR (CSR_ZZ02_MDIO_BASE + 0x28L)
#define CSR_ZZ02_MDIO_CSR_IV_2_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_2_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_2_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_2_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_2_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_2_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_2_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_2_read(a32);
	return zz02_mdio_csr_iv_2_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_3_ADDR (CSR_ZZ02_MDIO_BASE + 0x2cL)
#define CSR_ZZ02_MDIO_CSR_IV_3_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_3_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_3_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_3_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_3_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_3_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_3_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_3_read(a32);
	return zz02_mdio_csr_iv_3_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_4_ADDR (CSR_ZZ02_MDIO_BASE + 0x30L)
#define CSR_ZZ02_MDIO_CSR_IV_4_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_4_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_4_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_4_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_4_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_4_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_4_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_4_read(a32);
	return zz02_mdio_csr_iv_4_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_5_ADDR (CSR_ZZ02_MDIO_BASE + 0x34L)
#define CSR_ZZ02_MDIO_CSR_IV_5_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_5_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_5_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_5_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_5_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_5_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_5_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_5_read(a32);
	return zz02_mdio_csr_iv_5_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_6_ADDR (CSR_ZZ02_MDIO_BASE + 0x38L)
#define CSR_ZZ02_MDIO_CSR_IV_6_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_6_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_6_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_6_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_6_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_6_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_6_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_6_read(a32);
	return zz02_mdio_csr_iv_6_val_extract(a32, word);
}
#define CSR_ZZ02_MDIO_CSR_IV_7_ADDR (CSR_ZZ02_MDIO_BASE + 0x3cL)
#define CSR_ZZ02_MDIO_CSR_IV_7_SIZE 1
static inline uint32_t zz02_mdio_csr_iv_7_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ02_MDIO_CSR_IV_7_ADDR)));
}
#define CSR_ZZ02_MDIO_CSR_IV_7_VAL_OFFSET 0
#define CSR_ZZ02_MDIO_CSR_IV_7_VAL_SIZE 32
static inline uint32_t zz02_mdio_csr_iv_7_val_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 32)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz02_mdio_csr_iv_7_val_read(uint32_t a32) {
	uint32_t word = zz02_mdio_csr_iv_7_read(a32);
	return zz02_mdio_csr_iv_7_val_extract(a32, word);
}
#endif // CSR_ZZ02_MDIO_BASE

#endif
