//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2026-02-14 15:39:45
//--------------------------------------------------------------------------------
#ifndef __GENERATED_ZZ03_ETHPHY_CSR_H
#define __GENERATED_ZZ03_ETHPHY_CSR_H

/* zz03_ethphy */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_ZZ03_ETHPHY_BASE
#define CSR_ZZ03_ETHPHY_BASE (CSR_BASE + 0x1800L)
#define CSR_ZZ03_ETHPHY_MODE_DETECTION_MODE_ADDR (CSR_ZZ03_ETHPHY_BASE + 0x0L)
#define CSR_ZZ03_ETHPHY_MODE_DETECTION_MODE_SIZE 1
static inline uint32_t zz03_ethphy_mode_detection_mode_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_MODE_DETECTION_MODE_ADDR)));
}
#define CSR_ZZ03_ETHPHY_CRG_RESET_ADDR (CSR_ZZ03_ETHPHY_BASE + 0x4L)
#define CSR_ZZ03_ETHPHY_CRG_RESET_SIZE 1
static inline uint32_t zz03_ethphy_crg_reset_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_CRG_RESET_ADDR)));
}
static inline void zz03_ethphy_crg_reset_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_CRG_RESET_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ03_ETHPHY_MDIO_W_ADDR (CSR_ZZ03_ETHPHY_BASE + 0x8L)
#define CSR_ZZ03_ETHPHY_MDIO_W_SIZE 1
static inline uint32_t zz03_ethphy_mdio_w_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_MDIO_W_ADDR)));
}
static inline void zz03_ethphy_mdio_w_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_MDIO_W_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ03_ETHPHY_MDIO_W_MDC_OFFSET 0
#define CSR_ZZ03_ETHPHY_MDIO_W_MDC_SIZE 1
static inline uint32_t zz03_ethphy_mdio_w_mdc_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz03_ethphy_mdio_w_mdc_read(uint32_t a32) {
	uint32_t word = zz03_ethphy_mdio_w_read(a32);
	return zz03_ethphy_mdio_w_mdc_extract(a32, word);
}
static inline uint32_t zz03_ethphy_mdio_w_mdc_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz03_ethphy_mdio_w_mdc_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz03_ethphy_mdio_w_read(a32);
	uint32_t newword = zz03_ethphy_mdio_w_mdc_replace(a32, oldword, plain_value);
	zz03_ethphy_mdio_w_write(a32, newword);
}
#define CSR_ZZ03_ETHPHY_MDIO_W_OE_OFFSET 1
#define CSR_ZZ03_ETHPHY_MDIO_W_OE_SIZE 1
static inline uint32_t zz03_ethphy_mdio_w_oe_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 1) & mask );
}
static inline uint32_t zz03_ethphy_mdio_w_oe_read(uint32_t a32) {
	uint32_t word = zz03_ethphy_mdio_w_read(a32);
	return zz03_ethphy_mdio_w_oe_extract(a32, word);
}
static inline uint32_t zz03_ethphy_mdio_w_oe_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 1))) | (mask & plain_value)<< 1 ;
}
static inline void zz03_ethphy_mdio_w_oe_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz03_ethphy_mdio_w_read(a32);
	uint32_t newword = zz03_ethphy_mdio_w_oe_replace(a32, oldword, plain_value);
	zz03_ethphy_mdio_w_write(a32, newword);
}
#define CSR_ZZ03_ETHPHY_MDIO_W_W_OFFSET 2
#define CSR_ZZ03_ETHPHY_MDIO_W_W_SIZE 1
static inline uint32_t zz03_ethphy_mdio_w_w_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 2) & mask );
}
static inline uint32_t zz03_ethphy_mdio_w_w_read(uint32_t a32) {
	uint32_t word = zz03_ethphy_mdio_w_read(a32);
	return zz03_ethphy_mdio_w_w_extract(a32, word);
}
static inline uint32_t zz03_ethphy_mdio_w_w_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 2))) | (mask & plain_value)<< 2 ;
}
static inline void zz03_ethphy_mdio_w_w_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz03_ethphy_mdio_w_read(a32);
	uint32_t newword = zz03_ethphy_mdio_w_w_replace(a32, oldword, plain_value);
	zz03_ethphy_mdio_w_write(a32, newword);
}
#define CSR_ZZ03_ETHPHY_MDIO_R_ADDR (CSR_ZZ03_ETHPHY_BASE + 0xcL)
#define CSR_ZZ03_ETHPHY_MDIO_R_SIZE 1
static inline uint32_t zz03_ethphy_mdio_r_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ03_ETHPHY_MDIO_R_ADDR)));
}
#define CSR_ZZ03_ETHPHY_MDIO_R_R_OFFSET 0
#define CSR_ZZ03_ETHPHY_MDIO_R_R_SIZE 1
static inline uint32_t zz03_ethphy_mdio_r_r_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz03_ethphy_mdio_r_r_read(uint32_t a32) {
	uint32_t word = zz03_ethphy_mdio_r_read(a32);
	return zz03_ethphy_mdio_r_r_extract(a32, word);
}
#endif // CSR_ZZ03_ETHPHY_BASE

#endif
