//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2026-02-14 15:39:45
//--------------------------------------------------------------------------------
#ifndef __GENERATED_ZZ01_FB_CSR_H
#define __GENERATED_ZZ01_FB_CSR_H

/* zz01_fb */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_ZZ01_FB_BASE
#define CSR_ZZ01_FB_BASE (CSR_BASE + 0x1000L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_ENABLE_ADDR (CSR_ZZ01_FB_BASE + 0x0L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_ENABLE_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_enable_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_ENABLE_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_enable_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_ENABLE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HRES_ADDR (CSR_ZZ01_FB_BASE + 0x4L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HRES_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_hres_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HRES_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_hres_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HRES_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_START_ADDR (CSR_ZZ01_FB_BASE + 0x8L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_START_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_hsync_start_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_START_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_hsync_start_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_START_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_END_ADDR (CSR_ZZ01_FB_BASE + 0xcL)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_END_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_hsync_end_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_END_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_hsync_end_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSYNC_END_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSCAN_ADDR (CSR_ZZ01_FB_BASE + 0x10L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSCAN_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_hscan_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSCAN_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_hscan_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_HSCAN_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VRES_ADDR (CSR_ZZ01_FB_BASE + 0x14L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VRES_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_vres_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VRES_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_vres_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VRES_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_START_ADDR (CSR_ZZ01_FB_BASE + 0x18L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_START_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_vsync_start_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_START_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_vsync_start_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_START_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_END_ADDR (CSR_ZZ01_FB_BASE + 0x1cL)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_END_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_vsync_end_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_END_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_vsync_end_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSYNC_END_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSCAN_ADDR (CSR_ZZ01_FB_BASE + 0x20L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSCAN_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_vtg_vscan_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSCAN_ADDR)));
}
static inline void zz01_fb_video_framebuffer_vtg_vscan_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_VTG_VSCAN_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_BASE_ADDR (CSR_ZZ01_FB_BASE + 0x24L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_BASE_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_base_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_BASE_ADDR)));
}
static inline void zz01_fb_video_framebuffer_dma_base_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_BASE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LENGTH_ADDR (CSR_ZZ01_FB_BASE + 0x28L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LENGTH_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_length_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LENGTH_ADDR)));
}
static inline void zz01_fb_video_framebuffer_dma_length_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LENGTH_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_ENABLE_ADDR (CSR_ZZ01_FB_BASE + 0x2cL)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_ENABLE_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_enable_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_ENABLE_ADDR)));
}
static inline void zz01_fb_video_framebuffer_dma_enable_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_ENABLE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_DONE_ADDR (CSR_ZZ01_FB_BASE + 0x30L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_DONE_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_done_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_DONE_ADDR)));
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LOOP_ADDR (CSR_ZZ01_FB_BASE + 0x34L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LOOP_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_loop_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LOOP_ADDR)));
}
static inline void zz01_fb_video_framebuffer_dma_loop_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_LOOP_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_OFFSET_ADDR (CSR_ZZ01_FB_BASE + 0x38L)
#define CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_OFFSET_SIZE 1
static inline uint32_t zz01_fb_video_framebuffer_dma_offset_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ01_FB_VIDEO_FRAMEBUFFER_DMA_OFFSET_ADDR)));
}
#endif // CSR_ZZ01_FB_BASE

#endif
