//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2026-02-14 15:39:45
//--------------------------------------------------------------------------------
#ifndef __GENERATED_DDRPHY_CSR_H
#define __GENERATED_DDRPHY_CSR_H

/* ddrphy */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_DDRPHY_BASE
#define CSR_DDRPHY_BASE (CSR_BASE + 0x0L)
#define CSR_DDRPHY_RST_ADDR (CSR_DDRPHY_BASE + 0x0L)
#define CSR_DDRPHY_RST_SIZE 1
static inline uint32_t ddrphy_rst_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RST_ADDR)));
}
static inline void ddrphy_rst_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RST_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_DLY_SEL_ADDR (CSR_DDRPHY_BASE + 0x4L)
#define CSR_DDRPHY_DLY_SEL_SIZE 1
static inline uint32_t ddrphy_dly_sel_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_DLY_SEL_ADDR)));
}
static inline void ddrphy_dly_sel_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_DLY_SEL_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_HALF_SYS8X_TAPS_ADDR (CSR_DDRPHY_BASE + 0x8L)
#define CSR_DDRPHY_HALF_SYS8X_TAPS_SIZE 1
static inline uint32_t ddrphy_half_sys8x_taps_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_HALF_SYS8X_TAPS_ADDR)));
}
static inline void ddrphy_half_sys8x_taps_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_HALF_SYS8X_TAPS_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_WLEVEL_EN_ADDR (CSR_DDRPHY_BASE + 0xcL)
#define CSR_DDRPHY_WLEVEL_EN_SIZE 1
static inline uint32_t ddrphy_wlevel_en_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_WLEVEL_EN_ADDR)));
}
static inline void ddrphy_wlevel_en_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_WLEVEL_EN_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_WLEVEL_STROBE_ADDR (CSR_DDRPHY_BASE + 0x10L)
#define CSR_DDRPHY_WLEVEL_STROBE_SIZE 1
static inline uint32_t ddrphy_wlevel_strobe_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_WLEVEL_STROBE_ADDR)));
}
static inline void ddrphy_wlevel_strobe_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_WLEVEL_STROBE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_RDLY_DQ_RST_ADDR (CSR_DDRPHY_BASE + 0x14L)
#define CSR_DDRPHY_RDLY_DQ_RST_SIZE 1
static inline uint32_t ddrphy_rdly_dq_rst_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_RST_ADDR)));
}
static inline void ddrphy_rdly_dq_rst_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_RST_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_RDLY_DQ_INC_ADDR (CSR_DDRPHY_BASE + 0x18L)
#define CSR_DDRPHY_RDLY_DQ_INC_SIZE 1
static inline uint32_t ddrphy_rdly_dq_inc_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_INC_ADDR)));
}
static inline void ddrphy_rdly_dq_inc_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_INC_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_ADDR (CSR_DDRPHY_BASE + 0x1cL)
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_SIZE 1
static inline uint32_t ddrphy_rdly_dq_bitslip_rst_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_ADDR)));
}
static inline void ddrphy_rdly_dq_bitslip_rst_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_ADDR (CSR_DDRPHY_BASE + 0x20L)
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_SIZE 1
static inline uint32_t ddrphy_rdly_dq_bitslip_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_BITSLIP_ADDR)));
}
static inline void ddrphy_rdly_dq_bitslip_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDLY_DQ_BITSLIP_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_WDLY_DQ_BITSLIP_RST_ADDR (CSR_DDRPHY_BASE + 0x24L)
#define CSR_DDRPHY_WDLY_DQ_BITSLIP_RST_SIZE 1
static inline uint32_t ddrphy_wdly_dq_bitslip_rst_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_WDLY_DQ_BITSLIP_RST_ADDR)));
}
static inline void ddrphy_wdly_dq_bitslip_rst_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_WDLY_DQ_BITSLIP_RST_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_WDLY_DQ_BITSLIP_ADDR (CSR_DDRPHY_BASE + 0x28L)
#define CSR_DDRPHY_WDLY_DQ_BITSLIP_SIZE 1
static inline uint32_t ddrphy_wdly_dq_bitslip_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_WDLY_DQ_BITSLIP_ADDR)));
}
static inline void ddrphy_wdly_dq_bitslip_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_WDLY_DQ_BITSLIP_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_RDPHASE_ADDR (CSR_DDRPHY_BASE + 0x2cL)
#define CSR_DDRPHY_RDPHASE_SIZE 1
static inline uint32_t ddrphy_rdphase_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDPHASE_ADDR)));
}
static inline void ddrphy_rdphase_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_RDPHASE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_DDRPHY_WRPHASE_ADDR (CSR_DDRPHY_BASE + 0x30L)
#define CSR_DDRPHY_WRPHASE_SIZE 1
static inline uint32_t ddrphy_wrphase_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_DDRPHY_WRPHASE_ADDR)));
}
static inline void ddrphy_wrphase_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_DDRPHY_WRPHASE_ADDR + 0)) = __optional_bswap32(v);
}
#endif // CSR_DDRPHY_BASE

#endif
