//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a6d9955c) on 2026-02-14 15:39:45
//--------------------------------------------------------------------------------
#ifndef __GENERATED_ZZ04_ETHMAC_CSR_H
#define __GENERATED_ZZ04_ETHMAC_CSR_H

/* zz04_ethmac */
#ifndef CSR_BASE
#define CSR_BASE 0xa00000L
#endif
#ifndef CSR_ZZ04_ETHMAC_BASE
#define CSR_ZZ04_ETHMAC_BASE (CSR_BASE + 0x2000L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_SLOT_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x0L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_SLOT_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_slot_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_SLOT_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_LENGTH_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x4L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_LENGTH_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_length_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_LENGTH_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_ERRORS_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x8L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_ERRORS_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_errors_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_ERRORS_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_STATUS_ADDR (CSR_ZZ04_ETHMAC_BASE + 0xcL)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_STATUS_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_status_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_STATUS_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_STATUS_AVAILABLE_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_STATUS_AVAILABLE_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_status_available_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_writer_ev_status_available_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_writer_ev_status_read(a32);
	return zz04_ethmac_sram_writer_ev_status_available_extract(a32, word);
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x10L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_pending_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_ADDR)));
}
static inline void zz04_ethmac_sram_writer_ev_pending_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_AVAILABLE_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_PENDING_AVAILABLE_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_pending_available_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_writer_ev_pending_available_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_writer_ev_pending_read(a32);
	return zz04_ethmac_sram_writer_ev_pending_available_extract(a32, word);
}
static inline uint32_t zz04_ethmac_sram_writer_ev_pending_available_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz04_ethmac_sram_writer_ev_pending_available_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz04_ethmac_sram_writer_ev_pending_read(a32);
	uint32_t newword = zz04_ethmac_sram_writer_ev_pending_available_replace(a32, oldword, plain_value);
	zz04_ethmac_sram_writer_ev_pending_write(a32, newword);
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x14L)
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_enable_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_ADDR)));
}
static inline void zz04_ethmac_sram_writer_ev_enable_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_AVAILABLE_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_WRITER_EV_ENABLE_AVAILABLE_SIZE 1
static inline uint32_t zz04_ethmac_sram_writer_ev_enable_available_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_writer_ev_enable_available_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_writer_ev_enable_read(a32);
	return zz04_ethmac_sram_writer_ev_enable_available_extract(a32, word);
}
static inline uint32_t zz04_ethmac_sram_writer_ev_enable_available_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz04_ethmac_sram_writer_ev_enable_available_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz04_ethmac_sram_writer_ev_enable_read(a32);
	uint32_t newword = zz04_ethmac_sram_writer_ev_enable_available_replace(a32, oldword, plain_value);
	zz04_ethmac_sram_writer_ev_enable_write(a32, newword);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_START_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x18L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_START_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_start_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_START_ADDR)));
}
static inline void zz04_ethmac_sram_reader_start_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_START_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_READY_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x1cL)
#define CSR_ZZ04_ETHMAC_SRAM_READER_READY_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ready_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_READY_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_LEVEL_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x20L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_LEVEL_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_level_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_LEVEL_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_SLOT_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x24L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_SLOT_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_slot_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_SLOT_ADDR)));
}
static inline void zz04_ethmac_sram_reader_slot_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_SLOT_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_LENGTH_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x28L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_LENGTH_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_length_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_LENGTH_ADDR)));
}
static inline void zz04_ethmac_sram_reader_length_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_LENGTH_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_STATUS_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x2cL)
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_STATUS_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_status_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_EV_STATUS_ADDR)));
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_STATUS_EVENT0_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_STATUS_EVENT0_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_status_event0_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_reader_ev_status_event0_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_reader_ev_status_read(a32);
	return zz04_ethmac_sram_reader_ev_status_event0_extract(a32, word);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x30L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_pending_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_ADDR)));
}
static inline void zz04_ethmac_sram_reader_ev_pending_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_EVENT0_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_PENDING_EVENT0_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_pending_event0_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_reader_ev_pending_event0_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_reader_ev_pending_read(a32);
	return zz04_ethmac_sram_reader_ev_pending_event0_extract(a32, word);
}
static inline uint32_t zz04_ethmac_sram_reader_ev_pending_event0_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz04_ethmac_sram_reader_ev_pending_event0_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz04_ethmac_sram_reader_ev_pending_read(a32);
	uint32_t newword = zz04_ethmac_sram_reader_ev_pending_event0_replace(a32, oldword, plain_value);
	zz04_ethmac_sram_reader_ev_pending_write(a32, newword);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x34L)
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_enable_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_ADDR)));
}
static inline void zz04_ethmac_sram_reader_ev_enable_write(uint32_t a32, uint32_t v) {
	*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_ADDR + 0)) = __optional_bswap32(v);
}
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_EVENT0_OFFSET 0
#define CSR_ZZ04_ETHMAC_SRAM_READER_EV_ENABLE_EVENT0_SIZE 1
static inline uint32_t zz04_ethmac_sram_reader_ev_enable_event0_extract(uint32_t a32, uint32_t oldword) {
	uint32_t mask = ((1 << 1)-1);
	return ( (oldword >> 0) & mask );
}
static inline uint32_t zz04_ethmac_sram_reader_ev_enable_event0_read(uint32_t a32) {
	uint32_t word = zz04_ethmac_sram_reader_ev_enable_read(a32);
	return zz04_ethmac_sram_reader_ev_enable_event0_extract(a32, word);
}
static inline uint32_t zz04_ethmac_sram_reader_ev_enable_event0_replace(uint32_t a32, uint32_t oldword, uint32_t plain_value) {
	uint32_t mask = ((1 << 1)-1);
	return (oldword & (~(mask << 0))) | (mask & plain_value)<< 0 ;
}
static inline void zz04_ethmac_sram_reader_ev_enable_event0_write(uint32_t a32, uint32_t plain_value) {
	uint32_t oldword = zz04_ethmac_sram_reader_ev_enable_read(a32);
	uint32_t newword = zz04_ethmac_sram_reader_ev_enable_event0_replace(a32, oldword, plain_value);
	zz04_ethmac_sram_reader_ev_enable_write(a32, newword);
}
#define CSR_ZZ04_ETHMAC_PREAMBLE_CRC_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x38L)
#define CSR_ZZ04_ETHMAC_PREAMBLE_CRC_SIZE 1
static inline uint32_t zz04_ethmac_preamble_crc_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_PREAMBLE_CRC_ADDR)));
}
#define CSR_ZZ04_ETHMAC_RX_DATAPATH_PREAMBLE_ERRORS_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x3cL)
#define CSR_ZZ04_ETHMAC_RX_DATAPATH_PREAMBLE_ERRORS_SIZE 1
static inline uint32_t zz04_ethmac_rx_datapath_preamble_errors_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_RX_DATAPATH_PREAMBLE_ERRORS_ADDR)));
}
#define CSR_ZZ04_ETHMAC_RX_DATAPATH_CRC_ERRORS_ADDR (CSR_ZZ04_ETHMAC_BASE + 0x40L)
#define CSR_ZZ04_ETHMAC_RX_DATAPATH_CRC_ERRORS_SIZE 1
static inline uint32_t zz04_ethmac_rx_datapath_crc_errors_read(uint32_t a32) {
	return __optional_bswap32(*((volatile uint32_t*)(a32 + CSR_ZZ04_ETHMAC_RX_DATAPATH_CRC_ERRORS_ADDR)));
}
#endif // CSR_ZZ04_ETHMAC_BASE

#endif
